version: "3.1"
services:
  postgres-loms:
    image: postgres:15.1
    environment:
      POSTGRES_DB: loms
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./loms/pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d loms"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - net

  postgres-checkout:
    image: postgres:15.1
    environment:
      POSTGRES_DB: checkout
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./checkout/pgdata:/var/lib/postgresql/data
    ports:
      - 5433:5432
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d checkout"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - net

  checkout:
    image: checkout
    build: ./checkout/
    ports:
      - "8080:8080"
    depends_on: 
      postgres-checkout:
        condition: service_healthy
    networks:
      - net
  loms:
    image: loms
    build: ./loms/
    ports:
      - "8081:8081"
    depends_on: 
      postgres-loms:
        condition: service_healthy
    networks:
      - net
  # notification:
  #   image: notification
  #   build: ./notification
  #   ports:
  #     - "8082:8082"

networks:
  net:
    driver: bridge
